apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: tsb-gateway-eshop
  namespace: gitops-eshop
spec:
  revision: global
  kubeSpec:
    service:
      type: LoadBalancer
---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: tsb-gateway-payments
  namespace: gitops-eshop-payments
spec:
  revision: global
  kubeSpec:
    service:
      type: LoadBalancer
