---
apiVersion: api.tsb.tetrate.io/v2
kind: Tenant
metadata:
  organization: tetrate
  name: dev
spec:
  displayName: dev
---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  organization: tetrate
  tenant: dev
  name: bookinfo-ws-dev
spec:
  namespaceSelector:
    names:
      - "*/bookinfo-dev"
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  name: bookinfo-dev-gg
  organization: tetrate
  tenant: dev
  workspace: bookinfo-dev-ws
spec:
  namespaceSelector:
    names:
      - "*/bookinfo-dev"
  configMode: BRIDGED
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  name: bookinfo-dev-tg
  organization: tetrate
  tenant: dev
  workspace: bookinfo-dev-ws
spec:
  namespaceSelector:
    names:
      - "*/bookinfo-dev"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  name: bookinfo-dev-sg
  organization: tetrate
  tenant: dev
  workspace: bookinfo-dev-ws
spec:
  namespaceSelector:
    names:
      - "*/bookinfo-dev"
  configMode: BRIDGED
---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: bookinfo-dev-gw
  namespace: bookinfo-dev
spec:
  kubeSpec:
    service:
      type: LoadBalancer
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: bookinfo-dev-igw
  organization: tetrate
  tenant: dev
  workspace: bookinfo-dev-ws
  gatewayGroup: bookinfo-dev-gg
spec:
  workloadSelector:
    namespace: bookinfo-dev
    labels:
      app: bookinfo-dev-gw
  http:
    - name: productpage
      port: 80
      hostname: "bookinfo-dev.tetrate.io"
      routing:
        rules:
          - route:
              host: "bookinfo-dev/productpage.bookinfo-dev.svc.cluster.local"
              port: 9080
    - name: details
      port: 80
      hostname: "details-dev.tetrate.io"
      routing:
        rules:
          - route:
              host: "bookinfo-dev/details-dev.bookinfo-dev.svc.cluster.local"
              port: 9080
