---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookinfo-cert
  namespace: bookinfo-uat
spec:
  secretName: bookinfo-cert
  duration: 21600h # 900d
  issuerRef:
    name: selfsigned-ca
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "bookinfo-uat.tetrate.io"