apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: eshop-gateway
  namespace: eshop-config
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: eshop
    tsb.tetrate.io/workspace: eshop
    tsb.tetrate.io/gatewayGroup: eshop-gateways
spec:
  displayName: eShop Gateway
  http:
  - hostname: eshop.tetrate.io
    name: eshop
    port: 80
    routing:
      rules:
      - route:
          host: eshop/products.eshop.svc.cluster.local
          port: 80
    rateLimiting:
      settings:
        rules:
          - dimensions:
              - remoteAddress:
                  value: '*'
            limit:
              requestsPerUnit: 3
              unit: SECOND
  waf:
    rules:
      - Include @recommended-conf         # Recommended basic setup
      - SecRuleEngine On                  # Override DetectionOnly mode in @recommended-conf
      - SecResponseBodyAccess Off         # Override to not process response bodies
      - Include @crs-setup-conf           # Initialize the Core Rule Set
      - Include @owasp_crs/*.conf         # Load the Core Rule Set
      # Custom rule to deny requests with query parameter 'id=0'
      - SecRule ARGS:id "@eq 0" "id:1,phase:1,deny,status:403,msg:'Invalid id',log,auditlog"
  workloadSelector:
    labels:
      app: tsb-gateway-eshop
    namespace: eshop
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: payments-gateway
  namespace: eshop-config
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: eshop
    tsb.tetrate.io/workspace: payments
    tsb.tetrate.io/gatewayGroup: payments-gateways
spec:
  displayName: Payments Gateway
  http:
  - hostname: payments.tetrate.io
    name: payments
    port: 80
    routing:
      rules:
      - route:
          host: eshop-payments/payments.eshop-payments.svc.cluster.local
          port: 80
  workloadSelector:
    labels:
      app: tsb-gateway-payments
    namespace: eshop-payments
