apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-app-repo-bookinfo
spec:
  interval: 1m
  url: https://github.com/tetrateio/tetrate-service-bridge-sandbox
  ref:
    branch: fluxcd-demo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-bookinfo
spec:
  interval: 5m
  prune: true
  path: ./gitops/kustomize/applications/bookinfo
  sourceRef:
    kind: GitRepository
    name: flux-app-repo-bookinfo