---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookinfo-certificate
  namespace: bookinfo
spec:
  secretName: bookinfo-certificate
  duration: 21600h # 900d
  issuerRef:
    name: selfsigned-ca
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "bookinfo.tetrate.io"
