---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: trafficgenerator-bookinfo
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: trafficgenerator-bookinfo
      name: trafficgenerator-bookinfo
      namespace: trafficgenerator-bookinfo
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      selector:
        matchLabels:
          app: trafficgenerator-bookinfo
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: trafficgenerator-bookinfo
        spec:
          containers:
            - args:
                - /bin/sh
                - -c
                - 'while true; do sleep 60; curl -vIX GET -H"Host: internal-bookinfo.tetrate.io" bookinfo-gw.bookinfo/productpage; sleep 60; curl -vIX GET -H"Host: bookinfo.tetrate.io" tier1-gw.tier1/productpage; done'
              image: appropriate/curl
              imagePullPolicy: Always
              name: trafficgenerator-bookinfo
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always