---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        istio-injection: enabled
      name: egress
  - apiVersion: install.tetrate.io/v1alpha1
    kind: EgressGateway
    metadata:
      name: egress-gw
      namespace: egress
    spec:
      kubeSpec:
        service:
          type: LoadBalancer
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Gateway
    metadata:
      name: egress-gw
      namespace: egress
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-ws
        tsb.tetrate.io/gatewayGroup: bookinfo-gg
    spec:
      workloadSelector:
        namespace: egress
        labels:
          app: egress-gw
      http:
        - name: googleapis
          port: 80
          hostname: "www.googleapis.com"
          routing:
            rules:
              - route:
                  serviceDestination:
                    host: bookinfo/www.googleapis.com
                    port: 443
                    tls:
                      mode: SIMPLE
                      files:
                        caCertificates: "/etc/ssl/certs/ca-certificates.crt"
        - name: httpbin
          port: 80
          hostname: "httpbin.org"
          routing:
            rules:
              - route:
                  serviceDestination:
                    host: bookinfo/httpbin.org
                    port: 443
                    tls:
                      mode: SIMPLE
                      files:
                        caCertificates: "/etc/ssl/certs/ca-certificates.crt"
  - apiVersion: networking.istio.io/v1beta1
    kind: ServiceEntry
    metadata:
      name: www-googleapis-com
      namespace: egress
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-ws
        tsb.tetrate.io/istioInternalGroup: bookinfo-ig
      labels:
        istio.io/rev: tsb
    spec:
      hosts:
      - www.googleapis.com
      location: MESH_EXTERNAL
      exportTo:
      - "egress"
      ports:
      - number: 80
        name: http
        protocol: HTTP
      - number: 443
        name: https
        protocol: HTTPS
      resolution: DNS
  - apiVersion: networking.istio.io/v1beta1
    kind: ServiceEntry
    metadata:
      name: httpbin-org
      namespace: egress
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-ws
        tsb.tetrate.io/istioInternalGroup: bookinfo-ig
      labels:
        istio.io/rev: tsb
    spec:
      hosts:
      - httpbin.org
      location: MESH_EXTERNAL
      exportTo:
      - "egress"
      ports:
      - number: 80
        name: http
        protocol: HTTP
      - number: 443
        name: https
        protocol: HTTPS
      resolution: DNS