---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        istio-injection: enabled
      name: edge
  - apiVersion: install.tetrate.io/v1alpha1
    kind: Tier1Gateway
    metadata:
      name: edge-gw
      namespace: edge
    spec:
      kubeSpec:
        service:
          type: LoadBalancer
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Gateway
    metadata:
      name: edge-bookinfo-gw
      namespace: edge
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-ws
        tsb.tetrate.io/gatewayGroup: bookinfo-gg
    spec:
      workloadSelector:
        namespace: edge
        labels:
          app: edge-gw
      http:
        - name: productpage
          port: 80
          hostname: "bookinfo.tetrate.io"
          routing:
            rules:
              - route:
                  clusterDestination:
                    clusters: []
                modify:
                  rewrite:
                    authority: 'internal-bookinfo.tetrate.io'