---
apiVersion: v1
kind: List
items:
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: dev
      annotations:
        tsb.tetrate.io/organization: tetrate
      labels:
        domain: dev
    spec:
      description: dev
      displayName: dev
      deletionProtectionEnabled: true
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: bookinfo-qa-ws
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        owner: bookinfo-qa-ws-team
      labels:
        app: bookinfo-qa
    spec:
      isolationBoundary: qa
      namespaceSelector:
        names:
          - "*/bookinfo-qa"
          - "*/tier1-qa"
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-qa-gg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-qa-ws
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo-qa"
          - "*/tier1-qa"
      configMode: BRIDGED
  - apiVersion: traffic.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-qa-tg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-qa-ws
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo-qa"
          - "*/tier1-qa"
      configMode: BRIDGED
  - apiVersion: security.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-qa-sg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-qa-ws
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo-qa"
          - "*/tier1-qa"
      configMode: BRIDGED
  - apiVersion: istiointernal.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-qa-ig
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-qa-ws
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo"
          - "*/tier1-qa"
  - apiVersion: networking.istio.io/v1beta1
    kind: ServiceEntry
    metadata:
      name: www-googleapis-com
      namespace: bookinfo-qa
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-qa-ws
        tsb.tetrate.io/istioInternalGroup: bookinfo-qa-ig
      labels:
        istio.io/rev: tsb
    spec:
      hosts:
      - www.googleapis.com
      location: MESH_EXTERNAL
      ports:
      - number: 443
        name: https
        protocol: HTTPS
      resolution: DNS
  - apiVersion: install.tetrate.io/v1alpha1
    kind: IngressGateway
    metadata:
      name: bookinfo-qa-gw
      namespace: bookinfo-qa
    spec:
      revision: qa-stable
      kubeSpec:
        service:
          type: LoadBalancer
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Gateway
    metadata:
      name: bookinfo-qa-gw
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-qa-ws
        tsb.tetrate.io/gatewayGroup: bookinfo-qa-gg
    spec:
      workloadSelector:
        namespace: bookinfo-qa
        labels:
          app: bookinfo-qa-gw
      http:
        - name: productpage
          port: 80
          hostname: "bookinfo-qa.tetrate.io"
          routing:
            rules:
              - route:
                  serviceDestination:
                    host: "bookinfo-qa/productpage.bookinfo-qa.svc.cluster.local"
                    port: 9080
  - apiVersion: install.tetrate.io/v1alpha1
    kind: Tier1Gateway
    metadata:
      name: tier1-qa-gw
      namespace: tier1-qa
    spec:
      kubeSpec:
        service:
          type: LoadBalancer
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Gateway
    metadata:
      name: tier1-bookinfo-qa-gw
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-qa-ws
        tsb.tetrate.io/gatewayGroup: bookinfo-qa-gg
    spec:
      workloadSelector:
        namespace: tier1-qa
        labels:
          app: tier1-qa-gw
      http:
        - name: productpage
          port: 80
          hostname: "bookinfo-qa.tetrate.io"
          routing:
            rules:
              - route:
                  clusterDestination:
                    clusters: []
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: trafficgenerator-bookinfo-qa
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: trafficgenerator-bookinfo-qa
      name: trafficgenerator-bookinfo-qa
      namespace: trafficgenerator-bookinfo-qa
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      selector:
        matchLabels:
          app: trafficgenerator-bookinfo-qa
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: trafficgenerator-bookinfo-qa
        spec:
          containers:
            - args:
                - /bin/sh
                - -c
                - 'while true; do sleep 60; curl -vIX GET -H"Host: bookinfo-qa.tetrate.io" bookinfo-qa-gw.bookinfo-qa/productpage; curl -vIX GET -H"Host: bookinfo-qa.tetrate.io" tier1-qa-gw.tier1-qa/productpage; done'
              image: appropriate/curl
              imagePullPolicy: Always
              name: trafficgenerator-bookinfo-qa
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
---
