---
apiVersion: v1
kind: List
items:
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: dev
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      description: dev
      displayName: dev
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: gitops-bookinfo-qa-ws
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
    spec:
      namespaceSelector:
        names:
          - "*/gitops-bookinfo-qa"
          - "*/gitops-tier1-qa"
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: gitops-bookinfo-qa-gg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: gitops-bookinfo-qa-ws
    spec:
      namespaceSelector:
        names:
          - "*/gitops-bookinfo-qa"
          - "*/gitops-tier1-qa"
      configMode: BRIDGED
  - apiVersion: traffic.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: gitops-bookinfo-qa-tg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: gitops-bookinfo-qa-ws
    spec:
      namespaceSelector:
        names:
          - "*/gitops-bookinfo-qa"
          - "*/gitops-tier1-qa"
      configMode: BRIDGED
  - apiVersion: security.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: gitops-bookinfo-qa-sg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: gitops-bookinfo-qa-ws
    spec:
      namespaceSelector:
        names:
          - "*/gitops-bookinfo-qa"
          - "*/gitops-tier1-qa"
      configMode: BRIDGED
  - apiVersion: install.tetrate.io/v1alpha1
    kind: IngressGateway
    metadata:
      name: gitops-bookinfo-qa-gw
      namespace: gitops-bookinfo-qa
    spec:
      revision: qa-stable
      kubeSpec:
        service:
          type: LoadBalancer
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: IngressGateway
    metadata:
      name: gitops-bookinfo-qa-igw
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: gitops-bookinfo-qa-ws
        tsb.tetrate.io/gatewayGroup: gitops-bookinfo-qa-gg
    spec:
      workloadSelector:
        namespace: gitops-bookinfo-qa
        labels:
          app: gitops-bookinfo-qa-gw
      http:
        - name: productpage
          port: 80
          hostname: "gitops-bookinfo-qa.tetrate.io"
          routing:
            rules:
              - route:
                  host: "gitops-bookinfo-qa/productpage.gitops-bookinfo-qa.svc.cluster.local"
                  port: 9080
        - name: details
          port: 80
          hostname: "gitops-details.tetrate.io"
          routing:
            rules:
              - route:
                  host: "gitops-bookinfo-qa/details.gitops-bookinfo-qa.svc.cluster.local"
                  port: 9080
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: trafficgenerator
      name: trafficgenerator
      namespace: gitops-bookinfo-qa
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      selector:
        matchLabels:
          app: trafficgenerator
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: trafficgenerator
        spec:
          containers:
            - args:
                - /bin/sh
                - -c
                - 'while true; do curl -i -H"Host: gitops-bookinfo-qa.tetrate.io" gitops-bookinfo-qa-gw.gitops-bookinfo-qa/productpage; done'
              image: appropriate/curl
              imagePullPolicy: Always
              name: trafficgenerator
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
